BBBB BBBB BBBBBBBBBB
BBBBBBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX
        BB BBBBBBBBBBBBBBBB
            BBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Delete') XXXXXXXXX
        BBBBB
        BB BBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            BBBBB
        BBBBB


        BB BBBBBBBBB
        	XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Save') X XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
        BBBBB
        BB BBBBBBBBBBBBBBBB
        	XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Save as new') X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
        BBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBB
        	XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Save and add another') X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
        BBBBB
        BB BBBBBBBBBBBBBBBBBBBBBB
        	XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Save and continue editing') X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
        BBBBB

    XXXXX
XXXXXXXXX
