# Generated by Django 2.1.2 on 2018-11-12 00:21

from django.db import migrations, models
import math

def populate(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Fatture = apps.get_model('StudioLegale', 'Fatture')
    for fatture in Fatture.objects.all():
        fatture.trimestre_fattura = 'str(%s)-str(%s)' % (fatture.data_fattura.year, math.ceil(float(fatture.data_fattura.month) / 3))
        fatture.save()


class Migration(migrations.Migration):

    dependencies = [
        ('StudioLegale', '0001_squashed_0005_auto_20180527_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiosettorefattura1',
            options={'verbose_name': 'Studio Settore tipologia atto', 'verbose_name_plural': 'Studi Settore tipologia atto'},
        ),
        migrations.AlterModelOptions(
            name='studiosettorefattura2',
            options={'verbose_name': 'Studio Settore aree spec', 'verbose_name_plural': 'Studi Settore aree spec'},
        ),
        migrations.AddField(
            model_name='fatture',
            name='trimestre_fattura',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Trimestre fattura'),
        ),
        migrations.AlterField(
            model_name='fatture',
            name='anticipazioni',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='anticip.'),
        ),
        migrations.AlterField(
            model_name='fatture',
            name='cpa',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='tot c.p.a.'),
        ),
        migrations.AlterField(
            model_name='fatture',
            name='id_fattura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='fattura nu.'),
        ),
        migrations.AlterField(
            model_name='fatture',
            name='iva',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='tot iva'),
        ),
        migrations.AlterField(
            model_name='fatture',
            name='ritenuta',
            field=models.FloatField(default=0, null=True, verbose_name='tot r.a.'),
        ),
    ]
