# Generated by Django 2.1.2 on 2018-11-12 00:21

from django.db import migrations, models
import math

def populate(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Fatture = apps.get_model('StudioLegale', 'Fatture')
    for fatture in Fatture.objects.all():
        fatture.trimestre_fattura = '%s-%s' % (fatture.data_fattura.year, math.ceil(float(fatture.data_fattura.month) / 3))
        fatture.save()


class Migration(migrations.Migration):

    dependencies = [
        ('StudioLegale', '0002_auto_20181112_0021'),
    ]

    operations = [
        migrations.RunPython(populate, reverse_code=migrations.RunPython.noop),
    ]
